import { QRCodeSVG } from "qrcode.react";
import React from "react";

const Certificate = ({ studentName, batch, date }) => {
    return (
        <div className="certificate-container bg-white p-10 text-center border-[20px] border-double border-indigo-900 absolute top-0 left-0 w-full h-full flex flex-col justify-center items-center z-[9999]">
            <div className="border-4 border-indigo-100 h-full w-full p-8 flex flex-col justify-between relative">
                {/* Background Watermark */}
                <div className="absolute inset-0 flex items-center justify-center opacity-5 pointer-events-none">
                    <h1 className="text-[150px] font-black transform -rotate-45">NO DUE</h1>
                </div>

                <div>
                    <div className="flex justify-center items-center gap-4 mb-4">
                        <div className="text-4xl font-extrabold text-indigo-900 border-b-4 border-indigo-600 pb-2">NO DUE CERTIFICATE</div>
                    </div>
                    <p className="text-gray-500 uppercase tracking-[0.2em] font-bold text-sm">Official Clearance Document</p>
                </div>

                <div className="my-8">
                    <p className="text-lg italic text-gray-600 mb-2">This is to certify that</p>
                    <h1 className="text-5xl font-serif font-bold text-indigo-800 my-4 capitalize">{studentName}</h1>
                    <p className="text-lg text-gray-600">
                        Student of Batch <span className="font-bold text-black">{batch}</span>
                    </p>
                    <p className="text-gray-600 mt-4 max-w-2xl mx-auto leading-relaxed">
                        Has successfully cleared all dues and completed all assigned tasks from the respective departments.
                        There are no pending obligations against this student as of <span className="font-bold text-black">{date}</span>.
                    </p>
                </div>

                <div className="flex justify-between items-end mt-12 px-12">
                    <div className="text-center">
                        <div className="border-b-2 border-gray-400 w-48 mb-2"></div>
                        <p className="font-bold text-indigo-900">Principal / Auth Signatory</p>
                    </div>

                    <div className="flex flex-col items-center">
                        <QRCodeSVG
                            value={`CERT-NODUE-${studentName}-${batch}-${date}`}
                            size={100}
                            level={"H"}
                            includeMargin={true}
                            className="border-2 border-gray-200"
                        />
                        <p className="text-[10px] text-gray-400 mt-1 uppercase tracking-widest">Scan to Verify</p>
                    </div>

                    <div className="text-center">
                        <p className="font-bold text-lg text-indigo-900 mb-1">APPROVED</p>
                        <p className="text-sm text-green-600 font-bold border-2 border-green-600 px-2 py-1 inline-block rounded uppercase transform -rotate-12">
                            Verified
                        </p>
                    </div>
                </div>

                <div className="absolute bottom-4 left-0 w-full text-center">
                    <p className="text-[10px] text-gray-400">Generated by NoDueTracker System | This is a computer-generated document.</p>
                </div>
            </div>

            <style>{`
        @media print {
            @page { margin: 0; size: landscape; }
            body * { visibility: hidden; }
            .certificate-container, .certificate-container * { visibility: visible; }
            .certificate-container { position: absolute; left: 0; top: 0; width: 100vw; height: 100vh; margin: 0; border-width: 10px !important; }
            .btn-print { display: none !important; }
        }
    `}</style>
        </div>
    );
};

export default Certificate;
